<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Singarajan" failures="2" tests="21" name="com.AssessmentDimension.PostRequest" time="57.275" errors="0" timestamp="09 Jan 2023 08:15:49 GMT" skipped="0">
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="0.898"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST4" time="0.916"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST4" time="0.915"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST4" time="0.874"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST3" time="0.878"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST1" time="0.865"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST3" time="1.291"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST3" time="1.087">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.AssessmentDimension.PostRequest.testForPOST3(PostRequest.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testForPOST3 -->
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="0.945"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST1" time="0.857"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="1.057"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST1" time="0.875"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="0.893"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST1" time="0.864"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="0.895"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="0.898"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST4" time="38.439">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.AssessmentDimension.PostRequest.testForPOST4(PostRequest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testForPOST4 -->
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST3" time="1.109"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST2" time="0.888"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST4" time="0.877"/>
  <testcase classname="com.AssessmentDimension.PostRequest" name="testForPOST3" time="0.954"/>
</testsuite> <!-- com.AssessmentDimension.PostRequest -->
